version: '3.8'

# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: development
    volumes:
      - ./backend:/app
      - /app/__pycache__
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - HOT_RELOAD=true
    command: python -m uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_DEBUG=true
      - GENERATE_SOURCEMAP=true
    command: yarn start

  # Development database with persistent data
  mongodb:
    volumes:
      - ./data/mongodb-dev:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro