# Kubernetes deployment with secrets
apiVersion: v1
kind: Namespace
metadata:
  name: apigee-migration
---
# Secret for API keys and credentials
apiVersion: v1
kind: Secret
metadata:
  name: apigee-secrets
  namespace: apigee-migration
type: Opaque
stringData:
  # LLM API Keys
  OPENAI_API_KEY: "sk-your-openai-api-key-here"
  OPENAI_API_KEY: "sk-proj-your-openai-key"
  
  # Database credentials
  MONGO_ROOT_USERNAME: "apigee_admin"
  MONGO_ROOT_PASSWORD: "SecureMongo2024!"
  MONGO_DATABASE: "apigee_migration_db"
  
  # Security keys
  JWT_SECRET: "your-jwt-secret-key-here"
  ENCRYPTION_KEY: "your-encryption-key-here"
---
# ConfigMap for non-sensitive configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-config
  namespace: apigee-migration
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  FRONTEND_PORT: "3000"
  BACKEND_PORT: "8001"
  CORS_ORIGINS: "https://yourdomain.com"
  REACT_APP_BACKEND_URL: "https://api.yourdomain.com"
---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-backend
  namespace: apigee-migration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigee-backend
  template:
    metadata:
      labels:
        app: apigee-backend
    spec:
      containers:
      - name: backend
        image: apigee-migration-tool:backend
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: apigee-config
        - secretRef:
            name: apigee-secrets
        env:
        - name: MONGO_URL
          value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb:27017/$(MONGO_DATABASE)?authSource=admin"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 15
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigee-frontend
  namespace: apigee-migration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigee-frontend
  template:
    metadata:
      labels:
        app: apigee-frontend
    spec:
      containers:
      - name: frontend
        image: apigee-migration-tool:frontend
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: apigee-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: apigee-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: apigee-secrets
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "$(MONGO_ROOT_USERNAME)"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "$(MONGO_ROOT_PASSWORD)"
        - name: MONGO_INITDB_DATABASE
          value: "$(MONGO_DATABASE)"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: apigee-backend
  namespace: apigee-migration
spec:
  selector:
    app: apigee-backend
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-frontend
  namespace: apigee-migration
spec:
  selector:
    app: apigee-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: apigee-migration
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP